import { User } from "../models/usersModel.js";

const seedUsers = async () => {
  const users = [
    {
      name: "Oliver Smith",
      email: "oliver.smith@gmail.com",
      age: 23,
      role: "Admin",
      isActive: true,
      password: "Passw0rd@1",
    },
    {
      name: "Emma Johnson",
      email: "emma.johnson@yahoo.com",
      age: 29,
      role: "User",
      isActive: false,
      password: "S3cur3Pa$$",
    },
    {
      name: "Liam Williams",
      email: "liam.williams@outlook.com",
      age: 34,
      role: "Admin",
      isActive: true,
      password: "L1amW!lls2025",
    },
    {
      name: "Sophia Brown",
      email: "sophia.brown@icloud.com",
      age: 26,
      role: "User",
      isActive: true,
      password: "P@ssword123",
    },
    {
      name: "James Miller",
      email: "james.miller@hotmail.com",
      age: 32,
      role: "Admin",
      isActive: true,
      password: "J@mesM1llers",
    },
    {
      name: "Ava Davis",
      email: "ava.davis@gmail.com",
      age: 28,
      role: "User",
      isActive: false,
      password: "Ava@D@vis99",
    },
    {
      name: "Benjamin Wilson",
      email: "benjamin.wilson@gmail.com",
      age: 25,
      role: "Admin",
      isActive: true,
      password: "B3nJam!n",
    },
    {
      name: "Mia Moore",
      email: "mia.moore@yahoo.com",
      age: 31,
      role: "User",
      isActive: true,
      password: "M!aM0re10",
    },
    {
      name: "Lucas Taylor",
      email: "lucas.taylor@aol.com",
      age: 22,
      role: "Admin",
      isActive: false,
      password: "L#uc@5TayL",
    },
    {
      name: "Isabella Anderson",
      email: "isabella.anderson@outlook.com",
      age: 27,
      role: "User",
      isActive: true,
      password: "I$abella!32",
    },
    {
      name: "Ethan Thomas",
      email: "ethan.thomas@hotmail.com",
      age: 30,
      role: "Admin",
      isActive: true,
      password: "Ethan@Th0m@s",
    },
    {
      name: "Charlotte Jackson",
      email: "charlotte.jackson@yahoo.com",
      age: 25,
      role: "User",
      isActive: true,
      password: "Ch@rl0tte1",
    },
    {
      name: "Henry White",
      email: "henry.white@gmail.com",
      age: 38,
      role: "Admin",
      isActive: false,
      password: "H3nryW1te!",
    },
    {
      name: "Amelia Harris",
      email: "amelia.harris@icloud.com",
      age: 24,
      role: "User",
      isActive: true,
      password: "Am3l!@H@rris",
    },
    {
      name: "Alexander Martin",
      email: "alexander.martin@aol.com",
      age: 29,
      role: "Admin",
      isActive: true,
      password: "Alex@nd3r!",
    },
    {
      name: "Ella Thompson",
      email: "ella.thompson@gmail.com",
      age: 33,
      role: "User",
      isActive: false,
      password: "Ell@Th0mpS0n",
    },
    {
      name: "William Garcia",
      email: "william.garcia@yahoo.com",
      age: 40,
      role: "Admin",
      isActive: true,
      password: "W1ll!amGarc1@",
    },
    {
      name: "Olivia Martinez",
      email: "olivia.martinez@hotmail.com",
      age: 21,
      role: "User",
      isActive: true,
      password: "Ol1v!@M@rtinez",
    },
    {
      name: "Jack Rodriguez",
      email: "jack.rodriguez@aol.com",
      age: 35,
      role: "Admin",
      isActive: false,
      password: "J@ckRod1gu3z!",
    },
    {
      name: "Zoe Lee",
      email: "zoe.lee@gmail.com",
      age: 27,
      role: "User",
      isActive: true,
      password: "Zoe@L33!",
    },
    {
      name: "Sebastian Perez",
      email: "sebastian.perez@yahoo.com",
      age: 28,
      role: "Admin",
      isActive: true,
      password: "S3b@st1anP!r3z",
    },
    {
      name: "Grace Hall",
      email: "grace.hall@outlook.com",
      age: 29,
      role: "User",
      isActive: true,
      password: "Grace@H@ll",
    },
    {
      name: "David Young",
      email: "david.young@icloud.com",
      age: 32,
      role: "Admin",
      isActive: true,
      password: "Dav1dY0ung!",
    },
    {
      name: "Lily King",
      email: "lily.king@hotmail.com",
      age: 23,
      role: "User",
      isActive: true,
      password: "L!lyK1ng!",
    },
    {
      name: "Joseph Scott",
      email: "joseph.scott@gmail.com",
      age: 26,
      role: "Admin",
      isActive: true,
      password: "J0s3ph$@cotT",
    },
    {
      name: "Aria Green",
      email: "aria.green@aol.com",
      age: 24,
      role: "User",
      isActive: true,
      password: "Ar!@Gr33n",
    },
    {
      name: "Henry Adams",
      email: "henry.adams@outlook.com",
      age: 39,
      role: "Admin",
      isActive: false,
      password: "H3nry@Ad@ms",
    },
    {
      name: "Aiden Carter",
      email: "aiden.carter@yahoo.com",
      age: 30,
      role: "User",
      isActive: true,
      password: "AidenC@rt3r",
    },
    {
      name: "Natalie Mitchell",
      email: "natalie.mitchell@icloud.com",
      age: 32,
      role: "Admin",
      isActive: true,
      password: "Nat@l13Mitc#ll",
    },
    {
      name: "Samuel Perez",
      email: "samuel.perez@gmail.com",
      age: 28,
      role: "User",
      isActive: true,
      password: "S@m3uel!P3r",
    },
    {
      name: "Eleanor Clark",
      email: "eleanor.clark@aol.com",
      age: 26,
      role: "Admin",
      isActive: true,
      password: "EleanorC@1rk!",
    },
    {
      name: "Mason Walker",
      email: "mason.walker@hotmail.com",
      age: 29,
      role: "User",
      isActive: true,
      password: "M@sonW4lk3r",
    },
    {
      name: "Amos Brooks",
      email: "amos.brooks@outlook.com",
      age: 35,
      role: "Admin",
      isActive: false,
      password: "AmosBr00k$",
    },
    {
      name: "Madeline Green",
      email: "madeline.green@gmail.com",
      age: 40,
      role: "User",
      isActive: true,
      password: "M@d3lin3Gr33n",
    },
    {
      name: "Owen Harris",
      email: "owen.harris@yahoo.com",
      age: 31,
      role: "Admin",
      isActive: true,
      password: "Ow3nH@rr!s",
    },
    {
      name: "Chloe Allen",
      email: "chloe.allen@aol.com",
      age: 24,
      role: "User",
      isActive: true,
      password: "Chl0e@llEn",
    },
    {
      name: "Jacob Thomas",
      email: "jacob.thomas@hotmail.com",
      age: 33,
      role: "Admin",
      isActive: true,
      password: "J@c0bTh0m@s!",
    },
    {
      name: "Charlotte King",
      email: "charlotte.king@icloud.com",
      age: 30,
      role: "User",
      isActive: true,
      password: "Ch@rl0tt3K1ng!",
    },
    {
      name: "Ryan Scott",
      email: "ryan.scott@gmail.com",
      age: 22,
      role: "Admin",
      isActive: false,
      password: "R!y@nSc0tt",
    },
    {
      name: "Ella Lee",
      email: "ella.lee@aol.com",
      age: 25,
      role: "User",
      isActive: true,
      password: "Ell@L33e!",
    },
    {
      name: "Matthew Carter",
      email: "matthew.carter@outlook.com",
      age: 28,
      role: "Admin",
      isActive: true,
      password: "MatthewsC@rt3r",
    },
    {
      name: "Zoe Clark",
      email: "zoe.clark@yahoo.com",
      age: 27,
      role: "User",
      isActive: false,
      password: "Zoe@Cl@rk",
    },
    {
      name: "Michael Davis",
      email: "michael.davis@hotmail.com",
      age: 29,
      role: "Admin",
      isActive: true,
      password: "M!ch@elD@vis1",
    },
    {
      name: "Ella Robinson",
      email: "ella.robinson@outlook.com",
      age: 34,
      role: "User",
      isActive: true,
      password: "Ella@Rob1n",
    },
    {
      name: "Nolan Walker",
      email: "nolan.walker@aol.com",
      age: 38,
      role: "Admin",
      isActive: true,
      password: "N0lanW@lker",
    },
    {
      name: "Layla Moore",
      email: "layla.moore@gmail.com",
      age: 22,
      role: "User",
      isActive: true,
      password: "LaylaM00r3!",
    },
    {
      name: "Riley Lewis",
      email: "riley.lewis@yahoo.com",
      age: 27,
      role: "Admin",
      isActive: true,
      password: "R1l3yL3wis!",
    },
    {
      name: "Sophie Bennett",
      email: "sophie.bennett@icloud.com",
      age: 30,
      role: "User",
      isActive: true,
      password: "Soph!3B3nnetT",
    },
    {
      name: "Daniel Robinson",
      email: "daniel.robinson@hotmail.com",
      age: 28,
      role: "Admin",
      isActive: true,
      password: "D@n13lR0b1n",
    },
    {
      name: "Lily Hall",
      email: "lily.hall@outlook.com",
      age: 32,
      role: "User",
      isActive: true,
      password: "Lily@H@ll123",
    },
    {
      name: "Harper Miller",
      email: "harper.miller@gmail.com",
      age: 23,
      role: "Admin",
      isActive: false,
      password: "H@rperM1ll",
    },
    {
      name: "Madison Adams",
      email: "madison.adams@yahoo.com",
      age: 25,
      role: "User",
      isActive: true,
      password: "M@dis0nA1",
    },
    {
      name: "Grayson Wright",
      email: "grayson.wright@aol.com",
      age: 36,
      role: "Admin",
      isActive: true,
      password: "Gr@ys0nWri$ht",
    },
    {
      name: "Jackie Evans",
      email: "jackie.evans@icloud.com",
      age: 27,
      role: "User",
      isActive: true,
      password: "J@ck13Evans",
    },
    {
      name: "Daniel Gonzalez",
      email: "daniel.gonzalez@gmail.com",
      age: 32,
      role: "Admin",
      isActive: false,
      password: "D@n13lG0nz!",
    },
    {
      name: "Scarlett Parker",
      email: "scarlett.parker@hotmail.com",
      age: 28,
      role: "User",
      isActive: true,
      password: "Sc@r!3ttP@rk",
    },
  ];

  try {
    await User.bulkCreate(users);
    console.log("Users seeded successfully!");
  } catch (error) {
    console.error("Error seeding users:", error);
  }
};

seedUsers();
